### ISSUE TITLE
Promise should not leak thrown error in catch

### ISSUE THREAD

**Issue by jquense** [fluffynuts/synchronous-promise#11]
```js
let { SynchronousPromise }  = require("synchronous-promise")

let p = SynchronousPromise
    .reject(new Error())
    .catch(err => {
        throw err
    })
    .catch(err => {
        console.log('here')
    })
```

The above will throw the error outside the promise, so that the second catch never fires, when it it should catch a thrown error in `catch()` and pass it along

**Comment by fluffynuts** [comment]
Thanks for reporting! This is resolved in 2.0.5, which I just released.
