### ISSUE TITLE
node-ts usage

### ISSUE THREAD

**Issue by nikeee** [fluffynuts/synchronous-promise#14]
Owner of the npm package [`node-ts`](https://www.npmjs.com/package/node-ts) here. I'm suspecting that you actually want to install [`ts-node`](https://www.npmjs.com/package/ts-node) instead, since the library doesn't seem to look like it has anything to do with TeamSpeak.

**Comment by fluffynuts** [comment]
@nikeee 	thanks! I actually _do_ reference `ts-node`, for some TypeScript-specific workaround tests. I think I installed `node-ts` by accident ages ago and never properly uninstalled (:
