### ISSUE TITLE
Terminate function

### ISSUE THREAD

**Issue by cyberixae** [fluffynuts/synchronous-promise#16]
Does the library provide a terminate function that strips the Promise? This can not be done with actual promises but with a synchronous promise it should be doable.

```typescript
function terminate<A>(a: Promise<A>): A {
  // ...
}
```

**Comment by fluffynuts** [comment]
I'm not sure what you're trying to achieve with this?

SynchronousPromise doesn't store a resolved value inside the promise anywhere -- the moment a prior resolution happens, that value is passed down the chain.

You could patch SynchronousPromise like so:
```javascript
  SynchronousPromise.prototype.terminate = function() {
    let result;
    this.then(r => result = r);
    return result;
  }
```

It's not something I'd like to introduce to the library, but you're very welcome to patch it in your usage (:
