### ISSUE TITLE
This library does not work (or I am being extremely stupid)

### ISSUE THREAD

**Issue by DigitalLeaves** [fluffynuts/synchronous-promise#17]
Ok, probably the second one but...
I made a super simple test and realized that indeed SynchronousPromise does not work at all, or more specifically, works exactly as regular promises?

```
let { SynchronousPromise }  = require("synchronous-promise")

function waitThenTellNumber(i, callback) {
	const randomTime = Math.floor(Math.random() * 9000)+1000
	console.log("Starting task #"+i+", ETA: "+randomTime+"ms...")
	setTimeout(() => { console.log("Finished task #"+i); callback(true) }, randomTime)
}

const promises = []
for (let i = 0; i < 4; i++) {
	promises.push(new SynchronousPromise((resolve, reject) => { waitThenTellNumber(i, resolve) }))
}

console.log("Waiting some time before starting things...")
setTimeout(() => {
	SynchronousPromise.all(promises).then(values => { console.log("Finished "+value+" tasks") })
}, 3000)
```

The results are exactly the same that your everyday promise:
```
Starting task #0, ETA: 7157ms...
Starting task #1, ETA: 3826ms...
Starting task #2, ETA: 6426ms...
Starting task #3, ETA: 5428ms...
Waiting some time before starting things...
Finished task #1
Finished task #3
Finished task #2
Finished task #0
```

So maybe I am lost in translation here or I don't understand the meaning of "synchronous"...?

**Comment by fluffynuts** [comment]
`setTimeout` is asynchronous. If you put asynchronous code in a synchronous block, it's still asynchronous.

The use-case is for when the data source is _synchronous_. Compare the behavior of:

```javascript
let resolved = "nothing";
SynchronousPromise.resolve("foo").then(r => resolved = r);
console.log("resolved is: " + resolved);
```

vs

```javascript
let resolved = "nothing";
Promise.resolve("foo").then(r => resolved = r);
console.log("resolved is: " + resolved);
```

and you'll see what I mean.

SynchronousPromise can't interfere with other asynchronous code. I can't make XHRs synchronous. I can't make `setTimeout` synchronous. I can't make _other promise implementations_ synchronous. It's almost flattering that you expect that I could :D

**Comment by DigitalLeaves** [comment]
Of course, I realized that, that's why I closed it, thanks! 😊 Great library though.
