### ISSUE TITLE
finally() not passing result

### ISSUE THREAD

**Issue by epernice** [fluffynuts/synchronous-promise#18]
SynchronousPromise's `finally()` is not returning the resolved value (tried on 2.0.10). Here's a RunKit that compares the behavior against ES6 promises.
https://runkit.com/embed/cu88waw08blm

    var SynchronousPromise = require("synchronous-promise").SynchronousPromise;

    let result = null;

    result = await Promise.resolve("foo");
    console.log("es6 promise after resolve: " + result); // foo

    result = await SynchronousPromise.resolve("foo");
    console.log("sync promise after resolve: " + result); // foo

    result = await Promise.resolve("foo").finally();
    console.log("es6 promise after finally: " + result); // foo

    result = await SynchronousPromise.resolve("foo").finally();
    console.log("sync promise after finally: " + result); // undefined

**Comment by epernice** [comment]
Here's how I'm working around it. Not sure whether there will be problems associated with this hack.

    SynchronousPromise.prototype.finally = function(callback) {
        var ran = false;
        function runFinally() {
            if (!ran) {
                ran = true;
                return callback();
            }
        }
        return this
            .then(result => {
                runFinally();
                return result;
            })
            .catch(result => {
                runFinally();
                return result;
            });
    };

Thanks, by the way, for this library! It's going to save me a LOT of work as I move a large codebase off of angular 1.x promises (with $httpBackend flushing to make tests synchronous) over to ES6 promises. I really wasn't looking forward to modifying thousands of tests to use async/await.

**Comment by fluffynuts** [comment]
@epernice resolved & published. Thanks for reporting, especially in so much detail (:

**Comment by epernice** [comment]
Thanks for the quick turnaround!

The change does pass in my original Runkit, but still failed against my codebase. It looks like there is still an additional difference that crops up when a function is passed into the finally:

    var SynchronousPromise = require("synchronous-promise").SynchronousPromise;

    let result = null;

    result = await Promise.resolve("foo");
    console.log("es6 promise after resolve: " + result); // foo

    result = await SynchronousPromise.resolve("foo");
    console.log("sync promise after resolve: " + result); // foo

    result = await Promise.resolve("foo").finally(() => {});
    console.log("es6 promise after finally: " + result); // foo

    result = await SynchronousPromise.resolve("foo").finally(() => {});
    console.log("sync promise after finally: " + result); // undefined

**Comment by fluffynuts** [comment]
Ok, please check out 2.0.12 -- I added the test above (empty `finally` method) and then found that there were a couple of subtle differences between how native `Promise`s in Firefox behaved than how `SynchronousPromise` behaved, with respect to `finally` handling. Some of the behaviors don't seem logical to me -- like discarding the result from `finally` except if it throws, but that's what native FF promises do, so :shrug: I've implemented the same.

**Comment by fluffynuts** [comment]
should be fixed in 0042d623cb42390bcc9a53ce5a8fd2840aa81ae0

**Comment by fluffynuts** [comment]
btw, thanks for reporting -- as noted in the readme, I rely on user feedback to keep this library valuable (:

**Comment by epernice** [comment]
Sorry for not circling back to try this out sooner, but this solved it for me - thanks!
