### ISSUE TITLE
SynchronousPromise.any should reject with AggregateError object if supported

### ISSUE THREAD

**Issue by JoschuaSchneider** [fluffynuts/synchronous-promise#24]
The new `.any()` method is required by the [current spec](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise/any#Description) to reject with an [AggregateError](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/AggregateError) object.

This is implemented by all browsers that have the `Promise.any` method.

I would love to create a PR for that, and optionally return the AggregateError if in an supported browser environment.

**Comment by fluffynuts** [comment]
@JoschuaSchneider go for it (:
