### ISSUE TITLE
Problem calling "resolve" in constructor on promise value

### ISSUE THREAD

**Issue by joshuahhh** [fluffynuts/synchronous-promise#39]
I wrote a [little test](https://codepen.io/joshuahhh/pen/PoBEoOe) you can load. Here's the source:

```
import { SynchronousPromise } from "https://cdn.skypack.dev/synchronous-promise@2.0.16";

console.log("Start!");

function test(PromiseImpl, label) {
  console.log(label, ": Testing");
  const delay = new PromiseImpl((resolve) => setTimeout(() => resolve(100), 0));
  delay.then(() => console.log(label, ": delay is fulfilled"))
  const resolvedWithPromise = new PromiseImpl((resolve) => resolve(delay));
  resolvedWithPromise.then(() => console.log(label, ": resolvedWithPromise is fulfilled"))
};

test(Promise, "Promise");
test(SynchronousPromise, "SynchronousPromise");
```

In my browser, I get this console output:
```
Start!
Promise : Testing
SynchronousPromise : Testing
Promise : delay is fulfilled
Promise : resolvedWithPromise is fulfilled
SynchronousPromise : delay is fulfilled
```

Note that there's no "SynchronousPromise : resolvedWithPromise is fulfilled" line. For some reason, `resolvedWIthPromise` is never fulfilled when I use **SynchronousPromise**. I don't see why it shouldn't be fulfilled when `delay` is, as it is with **Promise**.

Any idea what might be going on? Please let me know if I can help. Thanks!

**Comment by fluffynuts** [comment]
@joshuahhh looks like a bug; a reordering of how things are done at resolution time passes a test based on your provided example code. Thanks for reporting & providing a succinct reproduction (:
